import type videojs from "video.js";
import type { BandwidthData, onLoadData, onLoadStartData, onPlaybackStateChangeData, onProgressData, onVolumeChangeData, TimedMetadata } from "../types/Events";
import type { TextTrack } from "../types/TextTrack";
import { type VideoRuntimeError } from "../types/VideoError";
import type { VideoPlayerStatus } from "../types/VideoPlayerStatus";
import type { AudioTrack } from "../types/AudioTrack";
import type { VideoTrack } from "../types/VideoTrack";
import type { QualityLevel } from "../types/QualityLevel";
import type { ListenerSubscription, VideoPlayerEventEmitterBase } from "../types/EventEmitter";
type VideoJsPlayer = ReturnType<typeof videojs>;
export declare class WebEventEmiter implements VideoPlayerEventEmitterBase {
    private player;
    private _isBuferring;
    private _listeners;
    constructor(player: VideoJsPlayer);
    destroy(): void;
    private _addListener;
    private _emit;
    addOnAudioBecomingNoisyListener(listener: () => void): ListenerSubscription;
    addOnAudioFocusChangeListener(listener: (hasAudioFocus: boolean) => void): ListenerSubscription;
    addOnBandwidthUpdateListener(listener: (data: BandwidthData) => void): ListenerSubscription;
    addOnBufferListener(listener: (buffering: boolean) => void): ListenerSubscription;
    addOnControlsVisibleChangeListener(listener: (visible: boolean) => void): ListenerSubscription;
    addOnEndListener(listener: () => void): ListenerSubscription;
    addOnExternalPlaybackChangeListener(listener: (externalPlaybackActive: boolean) => void): ListenerSubscription;
    addOnLoadListener(listener: (data: onLoadData) => void): ListenerSubscription;
    addOnLoadStartListener(listener: (data: onLoadStartData) => void): ListenerSubscription;
    addOnPlaybackStateChangeListener(listener: (data: onPlaybackStateChangeData) => void): ListenerSubscription;
    addOnPlaybackRateChangeListener(listener: (rate: number) => void): ListenerSubscription;
    addOnProgressListener(listener: (data: onProgressData) => void): ListenerSubscription;
    addOnReadyToDisplayListener(listener: () => void): ListenerSubscription;
    addOnSeekListener(listener: (position: number) => void): ListenerSubscription;
    addOnStatusChangeListener(listener: (status: VideoPlayerStatus) => void): ListenerSubscription;
    addOnTimedMetadataListener(listener: (data: TimedMetadata) => void): ListenerSubscription;
    addOnTextTrackDataChangedListener(listener: (data: string[]) => void): ListenerSubscription;
    addOnTrackChangeListener(listener: (track: TextTrack | null) => void): ListenerSubscription;
    addOnVolumeChangeListener(listener: (data: onVolumeChangeData) => void): ListenerSubscription;
    clearAllListeners(): void;
    addOnErrorListener(listener: (error: VideoRuntimeError) => void): ListenerSubscription;
    addOnAudioTrackChangeListener(listener: (track: AudioTrack | null) => void): ListenerSubscription;
    addOnVideoTrackChangeListener(listener: (track: VideoTrack | null) => void): ListenerSubscription;
    addOnQualityChangeListener(listener: (quality: QualityLevel) => void): ListenerSubscription;
    _onTimeUpdate(): void;
    _onCanPlay(): void;
    _onWaiting(): void;
    _onDurationChange(): void;
    _onEnded(): void;
    _onLoadStart(): void;
    _onPlay(): void;
    _onPause(): void;
    _onRateChange(): void;
    _onLoadedData(): void;
    _onSeeked(): void;
    _onVolumeChange(): void;
    _onError(): void;
    _onTextTrackChange(): void;
    _onAudioTrackChange(): void;
    _onVideoTrackChange(): void;
    _onQualityChange(): void;
}
export {};
//# sourceMappingURL=WebEventEmiter.d.ts.map